Add a Landing Section for Tech
ScottyLabs/web pull request #22
Opened 2022-07-29 06:45 UTC by jefferyjohn

Resolves #13 

## Desktop
![image](https://user-images.githubusercontent.com/53410876/181699348-7be593cf-5004-45a5-9770-b474fce5b946.png)

## Tablet
![image](https://user-images.githubusercontent.com/53410876/181699400-e0a0d92f-30b7-4689-93ae-dc6bc329713e.png)

## Mobile
![image](https://user-images.githubusercontent.com/53410876/181699465-d651391b-b4e5-43be-9446-5970328342a4.png)

2022-07-29 06:56 UTC, jefferyjohn commented
i can't tell if my div alignment is cursed would be v happy to change

2022-07-30 01:51 UTC, gramliu requested changes

2022-07-30 01:51 UTC, gramliu commented on pages/tech.tsx
> +      <div
Could you move the page styles to an [SCSS module](https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css)? It's generally cleaner since we can separate our styling into a separate file and have the component itself focus on the outline of elements.

I realized this was removed from the home page, since all the elements there are just sort of linear, but you can check out how we do it in the [Hero](https://github.com/ScottyLabs/scottylabs.org/tree/main/src/components/Hero) component, where we have a separate `index.module.scss` file. For page components, though, you can put the `scss` file in the `/styles` directory.

2022-07-30 01:51 UTC, gramliu commented on pages/tech.tsx
> +      <div
The advantage of using `scss` too is that we've defined different helper "functions" for dealing with responsive layouts. You can use something like:
```scss
  @include down($breakpoint-sm) {
    // css styles
  }
```
to create styles specific to mobile screens, for example. I'll try to create better documentation for these utilities soon.

2022-08-24 20:15 UTC, closed without merging